on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: api-food
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "18.x"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: config repository
        uses: actions/checkout@v2

      - name: set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install NPM packages and run build
        run: |
          npm install
          npm run build
  CD:
    name: "deploying"
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: config repository
        uses: actions/checkout@v2

      - name: add environments
        run: |
          touch .env
          echo DATABASE_PROD=${{ secrets.DATABASE_PROD }} >> .env
          echo TS_NODE_ENV=${{ secrets.TS_NODE_ENV }} >> .env

      - name: set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install NPM packages and run build
        run: |
          npm install
          npx prisma migrate deploy
          npm run build

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
