name: CI
on: 
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:  
    CI:  
      runs-on: ubuntu-latest
      steps:  
        - name: config repository
          uses: actions/checkout@v3.5.2
        - name: set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: install NPM packages
          run:  npm install
        - name: set up Environment Variables
          run: |
            echo "DATABASE_PROD=${{ secrets.DATABASE_PROD }}" >> $GITHUB_ENV
            echo "TS_NODE_ENV=${{ secrets.TS_NODE_ENV }}" >> $GITHUB_ENV
        - name: migrations prisma database
          run: npx prisma migrate dev
        - name: running script tests
          run: npm t
        - name: running scrupt build
          run: npm run build
              
    
