on:
  push:
    branches: 
      - master

env:
  AZURE_WEBAPP_NAME:  planned-food-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  NODE_VERSION: '18.x'               

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: config repository
        uses: actions/checkout@v2
     
      - name: set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install NPM packages and run build
        run: |
          npm install
          npm run build