name: CI-CD
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: config repository
        uses: actions/checkout@v3.5.2
      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install NPM packages
        run: npm install
      - name: set up Environment Variables
        run: |
          echo "DATABASE_PROD=${{ secrets.DATABASE_PROD }}" >> $GITHUB_ENV
          echo "TS_NODE_ENV=${{ secrets.TS_NODE_ENV }}" >> $GITHUB_ENV
      - name: migrations prisma database
        run: npx prisma migrate deploy
      - name: running script tests
        run: npm t
      - name: running scrupt build
        run: npm run build
  CD:
    runs-on: ubuntu-latest
    needs: CI
    environment:
      name: "production"
      url: planned-food-api.azurewebsites.net

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "planned-food-api"
          slot-name: "production"
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_7338d1ebff2944b4a48d5815e77121ae }}
